name: Publish thesis 
 
on:
  push:
    branches:
      - master
    paths:
      - 'monografia/**'
      - '.github/workflows/thesis.yml'
 
jobs:
  publish:
    name: Deploy thesis PDF
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: monografia.tex
          working_directory: monografia
 
      - name: Upload final PDF
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: monografia/monografia.pdf
          target: /srv/static/
          strip_components: 1
